### ISSUE TITLE
docs.rs not working

### ISSUE THREAD

**Issue by Foxcirc** [Foxcirc/pipedconsole#17]
**Description**
docs.rs does not compile correctly

**Expected behavior**
find documentation on docs.rs

**Solution**
Maybe replacing "\" with "/" inside the #[path] statement works.

**Comment by Boscop** [comment]
Docs.rs failed again with the latest version.

**Comment by Foxcirc** [comment]
Hey, I fixed the bug and I am waiting for docs.rs to build the package now.
Thank you!
